<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CapitalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $input = $_GET["country"];
        $countries = array('Afghanistan',
                          'Albania',
                          'Algeria',
                          'Andorra',
                          'Angola',
                          'Antigua and Barbuda',
                          'Argentina',
                          'Armenia',
                          'Australia',
                          'Austria',
                          'Azerbaijan',
                          'Bahamas',
                          'Bahrain',
                          'Bangladesh',
                          'Barbados',
                          'Belarus',
                          'Belgium',
                          'Belize',
                          'Benin',
                          'Bhutan',
                          'Bolivia',
                          'Bosnia and Herzegovina',
                          'Botswana',
                          'Brazil',
                          'Brunei',
                          'Bulgaria',
                          'Burkina Faso',
                          'Burundi',
                          'Cabo Verde',
                          'Cambodia',
                          'Cameroon',
                          'Canada',
                          'Central African Republic',
                          'Chad',
                          'Chile',
                          'China',
                          'Colombia',
                          'Comoros',
                          'Congo',
                          'Costa Rica',
                          'Croatia',
                          'Cuba',
                          'Cyprus',
                          'Czech Republic',
                          'Denmark',
                          'Djibouti',
                          'Dominica',
                          'Dominican Republic',
                          'Ecuador',
                          'Egypt',
                          'El Salvador',
                          'Equatorial Guinea',
                          'Eritrea',
                          'Estonia',
                          'Ethiopia',
                          'Fiji',
                          'Finland',
                          'France',
                          'Gabon',
                          'Gambia',
                          'Georgia',
                          'Germany',
                          'Ghana',
                          'Greece',
                          'Grenada',
                          'Guatemala',
                          'Guinea',
                          'Guinea-Bissau',
                          'Guyana',
                          'Haiti',
                          'Honduras',
                          'Hungary',
                          'Iceland',
                          'India',
                          'Indonesia',
                          'Iran',
                          'Iraq',
                          'Ireland',
                          'Israel',
                          'Italy',
                          'Jamaica',
                          'Japan',
                          'Jordan',
                          'Kazakhstan',
                          'Kenya',
                          'Kiribati',
                          'Kosovo',
                          'Kuwait',
                          'Kyrgyzstan',
                          'Laos',
                          'Latvia',
                          'Lebanon',
                          'Lesotho',
                          'Liberia',
                          'Libya',
                          'Liechtenstein',
                          'Lithuania',
                          'Luxembourg',
                          'Macedonia',
                          'Madagascar',
                          'Malawi',
                          'Malaysia',
                          'Maldives',
                          'Mali',
                          'Malta',
                          'Marshall Islands',
                          'Mauritania',
                          'Mauritius',
                          'Mexico',
                          'Micronesia',
                          'Moldova',
                          'Monaco',
                          'Mongolia',
                          'Montenegro',
                          'Morocco',
                          'Mozambique',
                          'Myanmar',
                          'Namibia',
                          'Nauru',
                          'Nepal',
                          'Netherlands',
                          'New Zealand',
                          'Nicaragua',
                          'Niger',
                          'Nigeria',
                          'North Korea',
                          'Norway',
                          'Oman',
                          'Pakistan',
                          'Palau',
                          'Palestine',
                          'Panama',
                          'Papua New Guinea',
                          'Paraguay',
                          'Peru',
                          'Philippines',
                          'Poland',
                          'Portugal',
                          'Qatar',
                          'Romania',
                          'Russia',
                          'Rwanda',
                          'Saint Kitts and Nevis',
                          'Saint Lucia',
                          'Saint Vincent and the Grenadines',
                          'Samoa',
                          'San Marino',
                          'Sao Tome and Principe',
                          'Saudi Arabia',
                          'Senegal',
                          'Serbia',
                          'Seychelles',
                          'Sierra Leone',
                          'Singapore',
                          'Slovakia',
                          'Slovenia',
                          'Solomon Islands',
                          'Somalia',
                          'South Africa',
                          'South Korea',
                          'South Sudan',
                          'Spain',
                          'Sri Lanka',
                          'Sudan',
                          'Suriname',
                          'Swaziland',
                          'Sweden',
                          'Switzerland',
                          'Syria',
                          'Taiwan',
                          'Tajikistan',
                          'Tanzania',
                          'Thailand',
                          'Timor-Leste',
                          'Togo',
                          'Tonga',
                          'Trinidad and Tobago',
                          'Tunisia',
                          'Turkey',
                          'Turkmenistan',
                          'Tuvalu',
                          'Uganda',
                          'Ukraine',
                          'United Arab Emirates',
                          'United Kingdom',
                          'United States of America',
                          'Uruguay',
                          'Uzbekistan',
                          'Vatican City',
                          'Venezuela',
                          'Vietnam',
                          'Yemen',
                          'Zambia',
                          'Zimbabwe',
                        );
        $capitals = array('Afghanistan' => 'Kabul',
                          'Albania' => 'Tirana',
                          'Algeria' => 'Algiers',
                          'Andorra' => 'Andorra la Vella',
                          'Angola' => 'Luanda',
                          'Antigua and Barbuda' => 'Saint John\'s',
                          'Argentina' => 'Buenos Aires',
                          'Armenia' => 'Yerevan',
                          'Australia' => 'Canberra',
                          'Austria' => 'Vienna',
                          'Azerbaijan' => 'Baku',
                          'Bahamas' => 'Nassau',
                          'Bahrain' => 'Manama',
                          'Bangladesh' => 'Dhaka',
                          'Barbados' => 'Bridgetown',
                          'Belarus' => 'Minsk',
                          'Belgium' => 'Brussels',
                          'Belize' => 'Belmopan',
                          'Benin' => 'Porto-Novo',
                          'Bhutan' => 'Thimphu',
                          'Bolivia' => 'Sucre and La Paz',
                          'Bosnia and Herzegovina' => 'Sarajevo',
                          'Botswana' => 'Gaborone',
                          'Brazil' => 'Brasilia',
                          'Brunei' => 'Bandar Seri Begawan',
                          'Bulgaria' => 'Sofia',
                          'Burkina Faso' => 'Ouagadougou',
                          'Burundi' => 'Bujumbura',
                          'Cabo Verde' => 'Praia',
                          'Cambodia' => 'Phnom Penh',
                          'Cameroon' => 'Yaounde',
                          'Canada' => 'Ottawa',
                          'Central African Republic' => 'Bangui',
                          'Chad' => 'N\'Djamena',
                          'Chile' => 'Santiago',
                          'China' => 'Beijing',
                          'Colombia' => 'Bogotá',
                          'Comoros' => 'Moroni',
                          'Congo' => 'Brazzaville',
                          'Costa Rica' => 'San Jose',
                          'Croatia' => 'Zagreb',
                          'Cuba' => 'Havana',
                          'Cyprus' => 'Nicosia',
                          'Czech Republic' => 'Prague',
                          'Denmark' => 'Copenhagen',
                          'Djibouti' => 'Djibouti',
                          'Dominica' => 'Roseau',
                          'Dominican Republic' => 'Santo Domingo',
                          'Ecuador' => 'Quito',
                          'Egypt' => 'Cairo',
                          'El Salvador' => 'San Salvador',
                          'Equatorial Guinea' => 'Malabo and Oyala',
                          'Eritrea' => 'Asmara',
                          'Estonia' => 'Tallinn',
                          'Ethiopia' => 'Addis Ababa',
                          'Fiji' => 'Suva',
                          'Finland' => 'Helsinki',
                          'France' => 'Paris',
                          'Gabon' => 'Libreville',
                          'Gambia' => 'Banjul',
                          'Georgia' => 'Tbilisi',
                          'Germany' => 'Berlin',
                          'Ghana' => 'Accra',
                          'Greece' => 'Athens',
                          'Grenada' => 'Saint George\'s',
                          'Guatemala' => 'Guatemala City',
                          'Guinea' => 'Conakry',
                          'Guinea-Bissau' => 'Bissau',
                          'Guyana' => 'Georgetown',
                          'Haiti' => 'Port-au-Prince',
                          'Honduras' => 'Tegucigalpa',
                          'Hungary' => 'Budapest',
                          'Iceland' => 'Reykjavik',
                          'India' => 'New Delhi',
                          'Indonesia' => 'Jakarta',
                          'Iran' => 'Tehran',
                          'Iraq' => 'Baghdad',
                          'Ireland' => 'Dublin',
                          'Israel' => 'Jerusalem',
                          'Italy' => 'Rome',
                          'Jamaica' => 'Kingston',
                          'Japan' => 'Tokyo',
                          'Jordan' => 'Amman',
                          'Kazakhstan' => 'Astana',
                          'Kenya' => 'Nairobi',
                          'Kiribati' => 'Tarawa',
                          'Kosovo' => 'Pristina',
                          'Kuwait' => 'Kuwait City',
                          'Kyrgyzstan' => 'Bishkek',
                          'Laos' => 'Vientiane',
                          'Latvia' => 'Riga',
                          'Lebanon' => 'Beirut',
                          'Lesotho' => 'Maseru',
                          'Liberia' => 'Monrovia',
                          'Libya' => 'Tripoli',
                          'Liechtenstein' => 'Vaduz',
                          'Lithuania' => 'Vilnius',
                          'Luxembourg' => 'Luxembourg City',
                          'Macedonia' => 'Skopje',
                          'Madagascar' => 'Antananarivo',
                          'Malawi' => 'Lilongwe',
                          'Malaysia' => 'Kuala Lumpur',
                          'Maldives' => 'Male',
                          'Mali' => 'Bamako',
                          'Malta' => 'Valletta',
                          'Marshall Islands' => 'Majuro',
                          'Mauritania' => 'Nouakchott',
                          'Mauritius' => 'Port Louis',
                          'Mexico' => 'Mexico City',
                          'Micronesia' => 'Palikir',
                          'Moldova' => 'Chisinau',
                          'Monaco' => 'Monaco',
                          'Mongolia' => 'Ulaanbaatar',
                          'Montenegro' => 'Podgorica',
                          'Morocco' => 'Rabat',
                          'Mozambique' => 'Maputo',
                          'Myanmar' => 'Naypyidaw',
                          'Namibia' => 'Windhoek',
                          'Nauru' => 'Yaren District',
                          'Nepal' => 'Kathmandu',
                          'Netherlands' => 'Amsterdam',
                          'New Zealand' => 'Wellington',
                          'Nicaragua' => 'Managua',
                          'Niger' => 'Niamey',
                          'Nigeria' => 'Abuja',
                          'North Korea' => 'Pyongyang',
                          'Norway' => 'Oslo',
                          'Oman' => 'Muscat',
                          'Pakistan' => 'Islamabad',
                          'Palau' => 'Ngerulmud',
                          'Palestine' => 'Jerusalem',
                          'Panama' => 'Panama City',
                          'Papua New Guinea' => 'Port Moresby',
                          'Paraguay' => 'Asunción',
                          'Peru' => 'Lima',
                          'Philippines' => 'Manila',
                          'Poland' => 'Warsaw',
                          'Portugal' => 'Lisbon',
                          'Qatar' => 'Doha',
                          'Romania' => 'Bucharest',
                          'Russia' => 'Moscow',
                          'Rwanda' => 'Kigali',
                          'Saint Kitts and Nevis' => 'Basseterre',
                          'Saint Lucia' => 'Castries',
                          'Saint Vincent and the Grenadines' => 'Kingstown',
                          'Samoa' => 'Apia',
                          'San Marino' => 'San Marino',
                          'Sao Tome and Principe' => 'São Tomé',
                          'Saudi Arabia' => 'Riyadh',
                          'Senegal' => 'Dakar',
                          'Serbia' => 'Belgrade',
                          'Seychelles' => 'Victoria',
                          'Sierra Leone' => 'Freetown',
                          'Singapore' => 'Singapore',
                          'Slovakia' => 'Bratislava',
                          'Slovenia' => 'Ljubljana',
                          'Solomon Islands' => 'Honiara',
                          'Somalia' => 'Mogadishu',
                          'South Africa' => 'Pretoria, Cape Town and Bloemfontein',
                          'South Korea' => 'Seoul',
                          'South Sudan' => 'Juba',
                          'Spain' => 'Madrid',
                          'Sri Lanka' => 'Sri Jayawardenepura Kotte',
                          'Sudan' => 'Khartoum',
                          'Suriname' => 'Paramaribo',
                          'Swaziland' => 'Mbabane and Lobamba',
                          'Sweden' => 'Stockholm',
                          'Switzerland' => 'Bern',
                          'Syria' => 'Damascus',
                          'Taiwan' => 'Taipei',
                          'Tajikistan' => 'Dushanbe',
                          'Tanzania' => 'Dodoma',
                          'Thailand' => 'Bangkok',
                          'Timor-Leste' => 'Dili',
                          'Togo' => 'Lomé',
                          'Tonga' => 'Nukuʻalofa',
                          'Trinidad and Tobago' => 'Port of Spain',
                          'Tunisia' => 'Tunis',
                          'Turkey' => 'Ankara',
                          'Turkmenistan' => 'Ashgabat',
                          'Tuvalu' => 'Funafuti',
                          'Uganda' => 'Kampala',
                          'Ukraine' => 'Kyiv',
                          'United Arab Emirates' => 'Abu Dhabi',
                          'United Kingdom' => 'London',
                          'United States of America' => 'Washington, D.C',
                          'Uruguay' => 'Montevideo',
                          'Uzbekistan' => 'Tashkent',
                          'Vanuatu' => 'Port Vila',
                          'Vatican City' => 'Vatican City',
                          'Venezuela' => 'Caracas',
                          'Vietnam' => 'Hanoi',
                          'Yemen' => 'Sana\'a',
                          'Zambia' => 'Lusaka',
                          'Zimbabwe' => 'Harare'
                        );
        $arrlength = count($countries);
        for ($i=0; $i < $arrlength; $i++) {
          if ($input == $countries[$i]) {
            echo "The capital of ".$input." is ".$capitals[$input].".";
          }
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
